# Generated by Django 3.2.8 on 2022-07-22 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commerce', '0003_auto_20220722_1234'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='img',
            field=models.ImageField(null=True, upload_to='products_images/', verbose_name='image'),
        ),
    ]
