# Generated by Django 3.2.8 on 2022-08-09 16:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('commerce', '0005_auto_20220731_1729'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='size',
        ),
        migrations.AddField(
            model_name='category',
            name='child',
            field=models.ManyToManyField(blank=True, null=True, related_name='_commerce_category_child_+', to='commerce.Category', verbose_name='child'),
        ),
        migrations.AddField(
            model_name='item',
            name='item_size',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='items', to='commerce.productsize', verbose_name='Size'),
        ),
    ]
