# Generated by Django 3.2.8 on 2022-08-09 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commerce', '0007_auto_20220809_2033'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='child',
        ),
        migrations.AddField(
            model_name='category',
            name='child',
            field=models.ManyToManyField(blank=True, null=True, related_name='_commerce_category_child_+', to='commerce.Category', verbose_name='child'),
        ),
    ]
