# Generated by Django 3.2.8 on 2022-09-05 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commerce', '0009_auto_20220809_2110'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='product_size',
            field=models.ManyToManyField(related_name='order', to='commerce.ProductSize', verbose_name='Size'),
        ),
    ]
