# Generated by Django 3.2.8 on 2022-09-05 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commerce', '0010_order_product_size'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='product_size',
        ),
        migrations.AddField(
            model_name='product',
            name='product_size',
            field=models.ManyToManyField(related_name='order', to='commerce.ProductSize', verbose_name='Size'),
        ),
    ]
