GET localhost:8000/api/auth
Content-Type: application/json
Accept: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwayI6ImQ3MDA1YjMxLTc3NDEtNDZlNi05NDFjLTM3YmQ1NWY2ZDM4ZiJ9.uwojP9bFnis3PRIzqG46fEUvlvmXfVLWG6kPUw8AmrU

###
POST localhost:8000/api/auth/signin
Content-Type: application/json
Accept: application/json

{
  "email": "u4@me.me",
  "password": "12345678!"
}

###
POST localhost:8000/api/auth/signup
Content-Type: application/json
Accept: application/json

{
  "first_name": "rb",
  "last_name": "rb",
  "email": "u2@gmail.com",
  "password1": "1234567!",
  "password2": "1234567!"
}
###
GET localhost:8000/api/auth
Content-Type: application/json
Accept: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwayI6ImQ3MDA1YjMxLTc3NDEtNDZlNi05NDFjLTM3YmQ1NWY2ZDM4ZiJ9.uwojP9bFnis3PRIzqG46fEUvlvmXfVLWG6kPUw8AmrU

###
PUT localhost:8000/api/auth
Content-Type: application/json
Accept: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwayI6ImQ3MDA1YjMxLTc3NDEtNDZlNi05NDFjLTM3YmQ1NWY2ZDM4ZiJ9.uwojP9bFnis3PRIzqG46fEUvlvmXfVLWG6kPUw8AmrU

{
  "first_name": "rb",
  "last_name": "al",
  "phone_number": "077",
  "address1": "Anything",
  "address2": "",
  "company_name": "",
  "company_website": ""
}


###
POST localhost:8000/api/auth/change-password
Content-Type: application/json
Accept: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwayI6ImQ3MDA1YjMxLTc3NDEtNDZlNi05NDFjLTM3YmQ1NWY2ZDM4ZiJ9.uwojP9bFnis3PRIzqG46fEUvlvmXfVLWG6kPUw8AmrU

{
  "old_password": "string!!",
  "new_password1": "!!123123!!",
  "new_password2": "!!123123!!"
}